// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtqaaldhjdjoqipbyodg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0cWFhbGRoamRqb3FpcGJ5b2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MTk5OTAsImV4cCI6MjA2MjQ5NTk5MH0.Pbl80yaXGAiNRHgMm9STGQSMdh0xwailxappuu7TyzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);